language: c
compiler:
  - clang
  - gcc
install:
  - sudo sh .travis/add-trusty
  - sudo apt-get update
  - sudo apt-get -t trusty install automake autoconf
  - sudo apt-get install
script: ./autogen.sh && ./configure --with-gtk && make
