language: c
sudo: required
dist: trusty
compiler:
  - clang
  - gcc
install:
  - sudo apt-get install gtk-doc-tools libudev-dev gobject-introspection automake autoconf
script: ./autogen.sh && ./configure --with-gtk && make
